name: picocog_dart
description: Picocog is a tiny Dart library for use in formatting text programatically (indents and placeholders) for the purposes of source code generation.
version: 1.0.6
homepage: https://github.com/ainslec/picocog-dart
repository: https://github.com/ainslec/picocog-dart
environment:
  sdk: '>=2.10.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
